### ISSUE TITLE
false positive `Unused.Dependencies`

### ISSUE THREAD

**Issue by lue-bird** [MartinSStewart/elm-review-bot#3]
`elm-review-bot` created a new [PR in `elm-bits`](https://github.com/lue-bird/elm-bits/pull/2#issue-977364526).
When I run the suggested
```noformat
npx elm-review --template jfmengels/elm-review-unused/example --rules NoUnused.Dependencies
```
or try running `elm-review` with the newest `elm-review-unused` dependency installed, no errors are found.

`elm-review-bot` however, suggests
```json
-   "lue-bird/elm-typed-value": "5.0.0 <= v < 6.0.0",
    "lue-bird/elm-typesafe-array": "18.0.0 <= v < 19.0.0"
},
"test-dependencies": {
+   "lue-bird/elm-typed-value": "5.0.0 <= v < 6.0.0"
}
```
This is probably (?) an issue with the used elm-review-unused version (bot uses 1.1.9, latest is 1.1.16).

**Comment by MartinSStewart** [comment]
I've seen some other people close PRs generated by the bot. This might explain why. I'll upgrade and hopefully that'll solve it!
